// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ewgroup_core_cpp
Rcpp::List ewgroup_core_cpp(const Rcpp::NumericMatrix& B, const Rcpp::NumericVector& Sigma_hat, const double sigma2, const double gamma, const bool return_jacobian, const bool return_weights);
RcppExport SEXP _ewgroup_ewgroup_core_cpp(SEXP BSEXP, SEXP Sigma_hatSEXP, SEXP sigma2SEXP, SEXP gammaSEXP, SEXP return_jacobianSEXP, SEXP return_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Sigma_hat(Sigma_hatSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_jacobian(return_jacobianSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_weights(return_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(ewgroup_core_cpp(B, Sigma_hat, sigma2, gamma, return_jacobian, return_weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ewgroup_ewgroup_core_cpp", (DL_FUNC) &_ewgroup_ewgroup_core_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ewgroup(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
