# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ewgroup_core_cpp <- function(B, Sigma_hat, sigma2, gamma, return_jacobian = TRUE, return_weights = TRUE) {
    .Call(`_ewgroup_ewgroup_core_cpp`, B, Sigma_hat, sigma2, gamma, return_jacobian, return_weights)
}
